//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace R10.Models
{
    public partial class Machine
    {
        public int Machine_ID { get; set; }
        public string Alias { get; set; }
        public string Machine_Name { get; set; }
        public string Machine_Class { get; set; }
        public string Machine_Owner_FirstName { get; set; }
        public string Machine_Owner_LastName { get; set; }
        public string Manufacturer { get; set; }
        public string Purchased_From { get; set; }
        public Nullable<System.DateTime> Purchase_Date { get; set; }
        public string Purchase_Details { get; set; }
        public string Model { get; set; }
        public string Serial { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> Shipping_Costs { get; set; }
        public Nullable<decimal> Additional_Cost { get; set; }
        public string Additional_Costs_Details { get; set; }
        public string Warranty_Details { get; set; }
        public Nullable<System.DateTime> Warranty_Expiration_Date { get; set; }
        public string Keys_1 { get; set; }
        public string Keys_2 { get; set; }
        public string Keys_3 { get; set; }
        public string Keys_4 { get; set; }
        public string External_Key { get; set; }
        public Nullable<int> Machine_Count_Order { get; set; }
        public string Machine_Notes { get; set; }
        public string Machine_Comments { get; set; }
        public string Location_Code { get; set; }
        public Nullable<System.DateTime> Record_Modify_Date { get; set; }
        public string Modifiers_Login { get; set; }
        public Nullable<bool> Data_Is_Dummy { get; set; }
        public Nullable<bool> Flagged_for_Deletion { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual LU_MachineClass LU_MachineClass { get; set; }
    }
    
}
