//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace R10.Models
{
    public partial class Action_Amusements_WinhostEntities : DbContext
    {
        public Action_Amusements_WinhostEntities()
            : base("name=Action_Amusements_WinhostEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<WorkOut> WorkOuts { get; set; }
        public DbSet<Workout_Got_Number> Workout_Got_Number { get; set; }
        public DbSet<Interview> Interviews { get; set; }
        public DbSet<Test_Date_Types> Test_Date_Types { get; set; }
        public DbSet<Test_SQL_DataTypes> Test_SQL_DataTypes { get; set; }
        public DbSet<Test_DateTime2_GetDate> Test_DateTime2_GetDate { get; set; }
        public DbSet<LU_MachineClass> LU_MachineClass { get; set; }
        public DbSet<Location> Locations { get; set; }
        public DbSet<Acc> Accs { get; set; }
        public DbSet<Machine> Machines { get; set; }
    }
}
