//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace R10.Models
{
    public partial class Acc
    {
        public Acc()
        {
            this.Locations = new HashSet<Location>();
        }
    
        public int Acc_ID { get; set; }
        public string Acc_Name { get; set; }
        public string Acc_Code { get; set; }
        public string Address1 { get; set; }
        public System.DateTime Begin_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public string Acc_Details { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State_Province_Territory { get; set; }
        public string Country { get; set; }
        public string Postal_Code { get; set; }
        public string Owner_FirstName { get; set; }
        public string Owner_LastName { get; set; }
        public string Owner_Cell { get; set; }
        public string Owner_Email { get; set; }
        public string Acc_Office_Phone { get; set; }
        public string Acc_Office_Fax { get; set; }
        public string Other_Office_Phone { get; set; }
        public string Other_Office_Fax { get; set; }
        public string POC_FirstName { get; set; }
        public string POC_LastName { get; set; }
        public string POC_Role { get; set; }
        public string POC_Email { get; set; }
        public string POC_Cell { get; set; }
        public string Notes { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> Record_Modify_Date { get; set; }
        public string Modifiers_Login { get; set; }
        public Nullable<bool> Data_Is_Dummy { get; set; }
        public Nullable<bool> Flagged_for_Deletion { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ICollection<Location> Locations { get; set; }
    }
    
}
