//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace R10.Models
{
    public partial class Test_SQL_DataTypes
    {
        public int ID { get; set; }
        public Nullable<System.TimeSpan> dt_Time { get; set; }
        public Nullable<System.DateTime> dt_datetime { get; set; }
        public string dt_Varchar { get; set; }
        public string dt_Nvarchar { get; set; }
        public string dt_char_4 { get; set; }
        public string dt_Nvarchar_MAX_COMMENTS { get; set; }
        public Nullable<bool> dt_Bit { get; set; }
        public Nullable<decimal> dt_Decimal_10_4 { get; set; }
        public Nullable<decimal> dt_Money { get; set; }
        public byte[] dt_Image { get; set; }
        public Nullable<decimal> dt_Numeric_10_3 { get; set; }
    }
    
}
