//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace R10.Models
{
    public partial class Test_DateTime2_GetDate
    {
        public int Id_PK_not_seed_nullable { get; set; }
        public Nullable<System.DateTime> dt_datetime2_GetDate_nullable { get; set; }
        public string comments_nulable { get; set; }
    }
    
}
