//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace R10.Models
{
    public partial class WorkOut
    {
        public int workout_ID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<short> DeadLift_final_set_Max { get; set; }
        public Nullable<short> Deadlift_Max_Weight { get; set; }
        public Nullable<short> ABS_Max_total_reps { get; set; }
        public Nullable<short> ABS_Max_total_reps_wieght { get; set; }
        public Nullable<short> ABS_Max_2Min { get; set; }
        public Nullable<short> Bench_max { get; set; }
        public Nullable<short> Bench_final_set_Max { get; set; }
        public Nullable<short> Bench_Max_wieght { get; set; }
        public Nullable<short> PushUp_final_Set_max { get; set; }
        public Nullable<short> Push_ups_Max_2min { get; set; }
        public Nullable<short> Biceps_curls_final_set_Max { get; set; }
        public Nullable<short> Biceps_curls_Wieght { get; set; }
        public Nullable<short> Biceps_Plate_final_set_Max { get; set; }
        public Nullable<short> Biceps_plate_Weight { get; set; }
        public Nullable<short> TBack_final_set_max { get; set; }
        public Nullable<short> TBack_Max_Weight { get; set; }
        public Nullable<short> Delt_Mil_press_final_Set_Max { get; set; }
        public Nullable<short> Delt_Mil_Press_Weight { get; set; }
        public Nullable<bool> Deltiod_2Min { get; set; }
        public Nullable<short> Obliques_final_rep_Max { get; set; }
        public Nullable<short> Obligues_Wieght { get; set; }
        public Nullable<bool> Run_3_sprint { get; set; }
        public Nullable<System.TimeSpan> Run_2mile_timed { get; set; }
        public Nullable<bool> DataISDumy { get; set; }
    }
    
}
