//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace R10.Models
{
    public partial class Interview
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Interview_Number { get; set; }
        public string Day { get; set; }
        public string Time { get; set; }
        public string Place { get; set; }
        public string Lead_Source { get; set; }
        public Nullable<bool> Staffing { get; set; }
        public string Interviewer1_Name { get; set; }
        public string Interviewer1_Role { get; set; }
        public string Interviewer2_Name { get; set; }
        public string Interviewer2_Role { get; set; }
        public string Interviewer3_Name { get; set; }
        public string Interviewer3_Role { get; set; }
        public string Interviewer_Phone { get; set; }
        public string Interview_email { get; set; }
        public string HR_Phone { get; set; }
        public string HR_email { get; set; }
        public string Recuiter_Phone { get; set; }
        public string Recuiter_email { get; set; }
        public string Other_Phone { get; set; }
        public string Other_email { get; set; }
        public string Interview_Type { get; set; }
        public string Test_Details { get; set; }
        public string Tech_Q_A { get; set; }
        public string Negotiation_Details { get; set; }
        public string Details { get; set; }
        public string Comments { get; set; }
        public string Improvements { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> Got_Job { get; set; }
        public string Position { get; set; }
        public string Pay { get; set; }
        public string Comp_Name { get; set; }
        public string Comp_Number { get; set; }
        public string Comp_URL { get; set; }
        public string Duration { get; set; }
        public string How_Ended { get; set; }
    }
    
}
