//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace R10.Models
{
    public partial class Workout_Got_Number
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Day { get; set; }
        public string Time { get; set; }
        public string Place { get; set; }
        public string Approach { get; set; }
        public string Method { get; set; }
        public string Rank { get; set; }
        public string M_Detials { get; set; }
        public Nullable<bool> Drink { get; set; }
        public Nullable<bool> Smoke { get; set; }
        public Nullable<bool> Card { get; set; }
        public Nullable<bool> Get_No { get; set; }
        public string Touch { get; set; }
        public string Improve { get; set; }
        public string Com { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string Nick { get; set; }
        public string Avail { get; set; }
        public string Duration { get; set; }
        public string HomeAdd { get; set; }
        public string WorkAdd { get; set; }
        public string NonVacAdd { get; set; }
        public string BornIn { get; set; }
        public string Money { get; set; }
        public string Age { get; set; }
        public string Eyes { get; set; }
        public string Other { get; set; }
        public Nullable<bool> Smoker { get; set; }
        public string Mobile { get; set; }
        public string OtherNo { get; set; }
        public string Email { get; set; }
    }
    
}
