//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace R10.Models
{
    public partial class Test_Date_Types
    {
        public int ID { get; set; }
        public string comments { get; set; }
        public Nullable<System.TimeSpan> dt_time { get; set; }
        public Nullable<System.DateTime> dt_date { get; set; }
        public Nullable<System.DateTime> dt_datetime { get; set; }
        public Nullable<System.DateTime> dt_datetime2 { get; set; }
        public byte[] dt_timestamp { get; set; }
        public System.DateTime Mod_Time_datetime { get; set; }
        public System.DateTime Mod_Time_datetime2 { get; set; }
        public string Modifiers_Login { get; set; }
    }
    
}
